module.exports = {
  Sulekha: {
    '#businessName': 'title',
    '#websiteUrl': 'url',
    '#email': 'email',
    '#category': 'category',
    '#address': 'address1',
    '#city': 'city',
    '#state': 'state',
    '#zip': 'pincode',
    '#phone': 'businessPhone',
    '#companyName': 'companyName',
    '#description': 'description',
  },
  JustDial: {
    '#businessName': 'title',
    '#website': 'url',
    '#email': 'email',
    '#category': 'category',
    '#address': 'address1',
    '#city': 'city',
    '#state': 'state',
    '#pincode': 'pincode',
    '#phone': 'businessPhone',
    '#companyName': 'companyName',
    '#description': 'description',
  },
  IndiaMart: {
    '#company': 'companyName',
    '#website': 'url',
    '#email': 'email',
    '#category': 'category',
    '#address': 'address1',
    '#city': 'city',
    '#state': 'state',
    '#zip': 'pincode',
    '#phone': 'businessPhone',
    '#description': 'description',
  },
  // Add more directories as needed
}; 